version: '3.3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - '3306:3306'

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  #web:
  #  depends_on:
  #    - db
  #  image: tomcat
  #  volumes:
  #    - ./target/twitter-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/twitter.war
  #  ports:
  #    - '8080:8080'
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: test_application
  #    MYSQL_USER: dev
  #    MYSQL_PASSWORD: dev