version: '3.3'
services:
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_application
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - '3306:3306'

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  web:
    depends_on:
      - db
    image: tomcat
    volumes:
      - ./target/application-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/application.war
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_application
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev