
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/twitter
    username: dev
    password: dev
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: true